### ISSUE TITLE
fp8 leads to black images (numerical instabilities) for transformer diffusion models

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/optimum-quanto#231]
I am on the `main` of quanto.

```python
from diffusers import DiffusionPipeline
import torch
from optimum.quanto import quantize, freeze, qfloat8_e4m3fn

pipeline_id = "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS": "pixart"
pipeline = DiffusionPipeline.from_pretrained(
    pipeline_id,
    torch_dtype=torch.float16
).to("cuda")

quantize(pipeline.transformer, weights=qfloat8_e4m3fn)
freeze(pipeline.transformer)

image = pipe(
    prompt="ghibli style, a fantasy landscape with castles",
    num_images_per_prompt=1,
    generator=torch.manual_seed(0),
).images[0]
```

leads to a black image

**Comment by dacorvo** [comment]
I reproduce the issue. Somewhere in the third encoder block `nan` outputs are generated. I suspect this comes from one the quantized weights after dequantization (and not from a `torch.float16` operation). I am checking them one by one to find out which.

**Comment by dacorvo** [comment]
It works well with int8 though ...

**Comment by dacorvo** [comment]
> Somewhere in the third transformer block nan outputs are generated. I suspect this comes from one the quantized weights after dequantization (and not from a torch.float16 operation)
So I was wrong: this was indeed an overflow in a `torch.float16` matmul, but only because I applied the `float8` quantization scale after the matmul. By applying the scale to the `float8` weights before the matmul they are back in the numerical range they had before quantization and the overflow disappears.

Here are the images generated with a float16 transformer and a float8 transformer (very subtle differences in the towers).

![bs@1-dtype@fp16-qtype@fp16](https://github.com/user-attachments/assets/3884a32c-881a-49e8-b9bf-0902c1dd360d)

![bs@1-dtype@fp16-qtype@fp8](https://github.com/user-attachments/assets/f45655b5-a285-4622-8332-be43e1dcfc23)

**Comment by dacorvo** [comment]
I am pushing the fix with a working example. I also quantized the text_encoder to make a real difference in size.

**Comment by songh11** [comment]
> 我处于`main`双币种状态。
> 
> ```python
> from diffusers import DiffusionPipeline
> import torch
> from optimum.quanto import quantize, freeze, qfloat8_e4m3fn
> 
> pipeline_id = "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS": "pixart"
> pipeline = DiffusionPipeline.from_pretrained(
>     pipeline_id,
>     torch_dtype=torch.float16
> ).to("cuda")
> 
> quantize(pipeline.transformer, weights=qfloat8_e4m3fn)
> freeze(pipeline.transformer)
> 
> image = pipe(
>     prompt="ghibli style, a fantasy landscape with castles",
>     num_images_per_prompt=1,
>     generator=torch.manual_seed(0),
> ).images[0]
> ```
> 
> 导致图像变黑

Hello, I wonder if the time spent has gone down?

**Comment by songh11** [comment]
> I am pushing the fix with a working example. I also quantized the text_encoder to make a real difference in size.

I also got a black images with fp8, and used more time. Do you know how to speed it up 
On 4090
| qtype | time |
|----|----|
| fp16 | 6.06s |
| fp8 | 7.22s |
| int8 | 16.16s |
