### ISSUE TITLE
Why latency of quantized model is even more than unquantized model?

### ISSUE THREAD

**Issue by ZhangYuef** [huggingface/optimum-quanto#232]
Based on my understanding, a quantized model (e.g., INT8 version) should run faster than an FP32 model, since the hardware has a specific acceleration unit for INT8 data computation. But the experimental results show that INT8 model suffers twice latency than FP16 model. 

Why this happens?

![image](https://github.com/huggingface/optimum-quanto/assets/20250982/0b252fd4-2e38-49ad-a3e4-f9b26f095290)

**Comment by dacorvo** [comment]
@ZhangYuef quantization has a cost, and even if it unlocks some operations optimized for lower data types, the overall resulting graph might be slower.
Regarding `int8` quantization, it can only shine when both activations and weights are `int8`, because we can use an accelerated integer matmul kernel: `torch._int_mm`.
However, as you can see in the middle graph, it actually doesn't, because there is a restriction on the input dimensions to be able to use that kernel: the first dimension of the input must be higher than 16.
Llama-3 is a generative model, whose inference comprises two phases:
- the encoding of the context,
- the iterative decoding of new tokens.
When encoding the context, the optimized kernel is called even if there is only one sequence to encode as long as the prompt contains more than 16 tokens.
When decoding, there is only one input token for each input sequence, which prevents us from using `torch._int_mm` if the batch_size is not > 16.
In the graph you selected, we are processing a single sequence, so the inference time is dominated by the sub-optimal decoding.

**Comment by dacorvo** [comment]
Here is the code that decides if we can use `torch._int_mm` or not:
https://github.com/huggingface/optimum-quanto/blob/fb505553be71175d013dc7eb0db104a151517b51/optimum/quanto/library/qbytes_mm.py#L79

**Comment by ZhangYuef** [comment]
Thanks for your detailed explaination. It seems that model compression does **not** necessarily lead to inference acceleration unless specialized matrix multiplication kernels (e.g., int8xFP16, int4xFP16) are implemented on specific hardware.
